/* Generated by Yosys 0.18+40 (git sha1 42721b6a1, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module aluStructural(A, B, Func_Sel, Y);
  wire [15:0] _00_;
  wire [31:0] _01_;
  wire _02_;
  wire _03_;
  wire [31:0] _04_;
  wire _05_;
  wire [31:0] _06_;
  wire [31:0] _07_;
  wire [31:0] _08_;
  wire [31:0] _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire [15:0] _14_;
  wire _15_;
  wire [31:0] _16_;
  wire _17_;
  input [15:0] A;
  wire [15:0] A;
  input [15:0] B;
  wire [15:0] B;
  input [3:0] Func_Sel;
  wire [3:0] Func_Sel;
  output [31:0] Y;
  wire [31:0] Y;
  wire ec;
  wire gc;
  wire lc;
  wire [15:0] ones_16;
  wire [31:0] ym;
  wire [15:0] yra;
  wire [15:0] ys;
  wire [15:0] zeros_16;
  wire [28:0] zeros_28;
  assign _17_ = Func_Sel == 4'h1;
  assign _01_ = yra[15] ? { ones_16, yra } : { zeros_16, yra };
  assign _02_ = Func_Sel == 4'h2;
  assign _03_ = Func_Sel == 4'h4;
  assign _04_ = ys[15] ? { ones_16, ys } : { zeros_16, ys };
  assign _05_ = Func_Sel == 4'h8;
  assign _06_ = _05_ ? ym : 32'd0;
  assign _07_ = _03_ ? _04_ : _06_;
  assign _08_ = _02_ ? { zeros_28, gc, lc, ec } : _07_;
  assign _09_ = _17_ ? _01_ : _08_;
  Comparator_16Bits c16 (
    .A(A),
    .B(B),
    .E(_13_),
    .G(_11_),
    .L(_12_)
  );
  Multiplier_16Bits m16 (
    .X(A),
    .Y(B),
    .Z(_16_)
  );
  Ripple_Adder_16Bits ra16 (
    .AAA(A),
    .BBB(B),
    .Cin3(1'h0),
    .Cout3(_10_),
    .YYY(_00_)
  );
  Subtractor_16Bits s16 (
    .A(A),
    .B(B),
    .Cout(_15_),
    .Y(_14_)
  );
  assign gc = _11_;
  assign lc = _12_;
  assign ec = _13_;
  assign yra = _00_;
  assign ys = _14_;
  assign ym = _16_;
  assign zeros_28 = 29'h00000000;
  assign zeros_16 = 16'h0000;
  assign ones_16 = 16'hffff;
  assign Y = _09_;
endmodule
