/* Generated by Yosys 0.18+40 (git sha1 42721b6a1, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module bidirectionalBehav(INPUT, CLK, Z1);
  reg [1:0] _00_;
  wire _01_;
  wire [1:0] _02_;
  wire [1:0] _03_;
  wire _04_;
  wire [1:0] _05_;
  wire _06_;
  wire [1:0] _07_;
  wire _08_;
  wire [1:0] _09_;
  wire _10_;
  input CLK;
  wire CLK;
  input INPUT;
  wire INPUT;
  output Z1;
  wire Z1;
  wire [1:0] ns;
  wire [1:0] ps;
  assign _04_ = ps == 2'h0;
  assign _05_ = INPUT ? 2'h2 : 2'h1;
  assign _06_ = ps == 2'h1;
  assign _07_ = INPUT ? 2'h0 : 2'h3;
  assign _08_ = ps == 2'h2;
  assign _09_ = INPUT ? 2'h2 : 2'h1;
  assign _10_ = ps == 2'h3;
  function [0:0] \33 ;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \33  = b[0:0];
      4'b??1?:
        \33  = b[1:1];
      4'b?1??:
        \33  = b[2:2];
      4'b1???:
        \33  = b[3:3];
      default:
        \33  = a;
    endcase
  endfunction
  assign _01_ = \33 (1'h0, 4'h8, { _10_, _08_, _06_, _04_ });
  function [1:0] \35 ;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \35  = b[1:0];
      4'b??1?:
        \35  = b[3:2];
      4'b?1??:
        \35  = b[5:4];
      4'b1???:
        \35  = b[7:6];
      default:
        \35  = a;
    endcase
  endfunction
  assign _02_ = \35 (2'h0, { _09_, _07_, _05_, _03_ }, { _10_, _08_, _06_, _04_ });
  always @(posedge CLK)
    _00_ <= ns;
  assign _03_ = INPUT ? 2'h0 : 2'h1;
  assign ps = _00_;
  assign ns = _02_;
  assign Z1 = _01_;
endmodule
