/* Generated by Yosys 0.18+40 (git sha1 42721b6a1, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module Full_Adder(Y, Z, Cin, Sum, Cout);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  input Cin;
  wire Cin;
  output Cout;
  wire Cout;
  output Sum;
  wire Sum;
  input Y;
  wire Y;
  input Z;
  wire Z;
  wire yxz;
  assign _0_ = Y ^ Z;
  assign _1_ = yxz ^ Cin;
  assign _2_ = Y & Z;
  assign _3_ = Z & Cin;
  assign _4_ = _2_ | _3_;
  assign _5_ = Cin & Y;
  assign _6_ = _4_ | _5_;
  assign yxz = _0_;
  assign Sum = _1_;
  assign Cout = _6_;
endmodule
