/* Generated by Yosys 0.18+40 (git sha1 42721b6a1, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module Ripple_Adder_8Bits(AA0, AA1, AA2, AA3, AA4, AA5, AA6, AA7, BB0, BB1, BB2, BB3, BB4, BB5, BB6, BB7, Cin2, YY0, YY1, YY2, YY3
, YY4, YY5, YY6, YY7, Cout2);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  input AA0;
  wire AA0;
  input AA1;
  wire AA1;
  input AA2;
  wire AA2;
  input AA3;
  wire AA3;
  input AA4;
  wire AA4;
  input AA5;
  wire AA5;
  input AA6;
  wire AA6;
  input AA7;
  wire AA7;
  input BB0;
  wire BB0;
  input BB1;
  wire BB1;
  input BB2;
  wire BB2;
  input BB3;
  wire BB3;
  input BB4;
  wire BB4;
  input BB5;
  wire BB5;
  input BB6;
  wire BB6;
  input BB7;
  wire BB7;
  input Cin2;
  wire Cin2;
  output Cout2;
  wire Cout2;
  output YY0;
  wire YY0;
  output YY1;
  wire YY1;
  output YY2;
  wire YY2;
  output YY3;
  wire YY3;
  output YY4;
  wire YY4;
  output YY5;
  wire YY5;
  output YY6;
  wire YY6;
  output YY7;
  wire YY7;
  wire c0;
  Ripple_Adder_4Bit ra40 (
    .A0(AA0),
    .A1(AA1),
    .A2(AA2),
    .A3(AA3),
    .B0(BB0),
    .B1(BB1),
    .B2(BB2),
    .B3(BB3),
    .Cin1(Cin2),
    .Cout1(_0_),
    .Y0(_2_),
    .Y1(_3_),
    .Y2(_4_),
    .Y3(_5_)
  );
  Ripple_Adder_4Bit ra41 (
    .A0(AA4),
    .A1(AA5),
    .A2(AA6),
    .A3(AA7),
    .B0(BB4),
    .B1(BB5),
    .B2(BB6),
    .B3(BB7),
    .Cin1(c0),
    .Cout1(_6_),
    .Y0(_7_),
    .Y1(_8_),
    .Y2(_9_),
    .Y3(_1_)
  );
  assign c0 = _0_;
  assign YY0 = _2_;
  assign YY1 = _3_;
  assign YY2 = _4_;
  assign YY3 = _5_;
  assign YY4 = _7_;
  assign YY5 = _8_;
  assign YY6 = _9_;
  assign YY7 = _1_;
  assign Cout2 = _6_;
endmodule
