/* Generated by Yosys 0.18+40 (git sha1 42721b6a1, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module Ripple_Adder_32Bits(AAAA, BBBB, Cin4, YYYY, Cout4);
  wire [15:0] _0_;
  wire _1_;
  wire [15:0] _2_;
  wire _3_;
  input [31:0] AAAA;
  wire [31:0] AAAA;
  input [31:0] BBBB;
  wire [31:0] BBBB;
  input Cin4;
  wire Cin4;
  output Cout4;
  wire Cout4;
  output [31:0] YYYY;
  wire [31:0] YYYY;
  wire c0;
  Ripple_Adder_16Bits ra160 (
    .AAA(AAAA[15:0]),
    .BBB(BBBB[15:0]),
    .Cin3(Cin4),
    .Cout3(_1_),
    .YYY(_0_)
  );
  Ripple_Adder_16Bits ra161 (
    .AAA(AAAA[31:16]),
    .BBB(BBBB[31:16]),
    .Cin3(c0),
    .Cout3(_3_),
    .YYY(_2_)
  );
  assign c0 = _1_;
  assign YYYY = { _2_, _0_ };
  assign Cout4 = _3_;
endmodule
