/* Generated by Yosys 0.18+40 (git sha1 42721b6a1, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module Ripple_Adder_4Bit(A0, A1, A2, A3, B0, B1, B2, B3, Cin1, Cout1, Y0, Y1, Y2, Y3);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  input A0;
  wire A0;
  input A1;
  wire A1;
  input A2;
  wire A2;
  input A3;
  wire A3;
  input B0;
  wire B0;
  input B1;
  wire B1;
  input B2;
  wire B2;
  input B3;
  wire B3;
  input Cin1;
  wire Cin1;
  output Cout1;
  wire Cout1;
  output Y0;
  wire Y0;
  output Y1;
  wire Y1;
  output Y2;
  wire Y2;
  output Y3;
  wire Y3;
  wire c0;
  wire c1;
  wire c2;
  wire c3;
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  Full_Adder fa0 (
    .Cin(Cin1),
    .Cout(_1_),
    .Sum(_0_),
    .Y(A0),
    .Z(B0)
  );
  Full_Adder fa1 (
    .Cin(c0),
    .Cout(_3_),
    .Sum(_2_),
    .Y(A1),
    .Z(B1)
  );
  Full_Adder fa2 (
    .Cin(c1),
    .Cout(_5_),
    .Sum(_4_),
    .Y(A2),
    .Z(B2)
  );
  Full_Adder fa3 (
    .Cin(c2),
    .Cout(_7_),
    .Sum(_6_),
    .Y(A3),
    .Z(B3)
  );
  assign c0 = _1_;
  assign c1 = _3_;
  assign c2 = _5_;
  assign c3 = _7_;
  assign s0 = _0_;
  assign s1 = _2_;
  assign s2 = _4_;
  assign s3 = _6_;
  assign Cout1 = c3;
  assign Y0 = s0;
  assign Y1 = s1;
  assign Y2 = s2;
  assign Y3 = s3;
endmodule
