/* Generated by Yosys 0.18+40 (git sha1 42721b6a1, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module Ripple_Adder_16Bits(AAA, BBB, Cin3, YYY, Cout3);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  input [15:0] AAA;
  wire [15:0] AAA;
  input [15:0] BBB;
  wire [15:0] BBB;
  input Cin3;
  wire Cin3;
  output Cout3;
  wire Cout3;
  output [15:0] YYY;
  wire [15:0] YYY;
  wire c0;
  Ripple_Adder_8Bits ra80 (
    .AA0(AAA[0]),
    .AA1(AAA[1]),
    .AA2(AAA[2]),
    .AA3(AAA[3]),
    .AA4(AAA[4]),
    .AA5(AAA[5]),
    .AA6(AAA[6]),
    .AA7(AAA[7]),
    .BB0(BBB[0]),
    .BB1(BBB[1]),
    .BB2(BBB[2]),
    .BB3(BBB[3]),
    .BB4(BBB[4]),
    .BB5(BBB[5]),
    .BB6(BBB[6]),
    .BB7(BBB[7]),
    .Cin2(Cin3),
    .Cout2(_17_),
    .YY0(_00_),
    .YY1(_10_),
    .YY2(_11_),
    .YY3(_12_),
    .YY4(_13_),
    .YY5(_14_),
    .YY6(_15_),
    .YY7(_16_)
  );
  Ripple_Adder_8Bits ra81 (
    .AA0(AAA[8]),
    .AA1(AAA[9]),
    .AA2(AAA[10]),
    .AA3(AAA[11]),
    .AA4(AAA[12]),
    .AA5(AAA[13]),
    .AA6(AAA[14]),
    .AA7(AAA[15]),
    .BB0(BBB[8]),
    .BB1(BBB[9]),
    .BB2(BBB[10]),
    .BB3(BBB[11]),
    .BB4(BBB[12]),
    .BB5(BBB[13]),
    .BB6(BBB[14]),
    .BB7(BBB[15]),
    .Cin2(c0),
    .Cout2(_09_),
    .YY0(_01_),
    .YY1(_02_),
    .YY2(_03_),
    .YY3(_04_),
    .YY4(_05_),
    .YY5(_06_),
    .YY6(_07_),
    .YY7(_08_)
  );
  assign c0 = _17_;
  assign YYY = { _08_, _07_, _06_, _05_, _04_, _03_, _02_, _01_, _16_, _15_, _14_, _13_, _12_, _11_, _10_, _00_ };
  assign Cout3 = _09_;
endmodule
